### ISSUE TITLE
Scroll binding toggle key

### ISSUE THREAD

**Issue by robcsi** [q335r49/microviche#1]
Hi,

I like the plugin, and I've been experimenting with it.
There is mention of Scrollbinding in the docs and videos, but I just can't manage to toggle it.

Can you please tell me how it can be done?

Thanks,
robcsi

**Comment by q335r49** [comment]
Hey robsci,

I used to have a global scrollbindnig toggle but unfortunately I removed it because I wasn't using it. You would have to do it split by split unfortunately. 

The F10,E "Edit split" command will allow you to change an "Autoexecute on load:" setting, where the default is "se scb nowrap cole=2".

You would have to change scb ('scrollbind') setting to noscb, ie, "se noscb nowrap cole=2"

You can automate this by playing with the the t:txb.exe variable, the list of all the autoexecutes in order, eg:

for i in len(t:txb.exe)
   let t:txb.exe[i]='se noscb nowrap cole=2'
endfor.

I'll do somethign about exposing the default autoexecute in the next version

Thanks,

Leon

**Comment by robcsi** [comment]
Thanks. 

I think it would be helpful to make it available, I can see many situations when people would like to be able to change the default globally, especially in programming.

**Comment by q335r49** [comment]
Not a bad idea... I'll throw it in

**Comment by robcsi** [comment]
Hi Leon,

Thanks for adding the settings window with all the options. It's much easier now to set the values I want.

I'm closing the 2 issues.

Cheers,
robcsi
