### ISSUE TITLE
f10 not working

### ISSUE THREAD

**Issue by joakin** [q335r49/microviche#4]
Hi!
I've tried to use textabyss but I'm getting some trouble.

I cloned the repo with Vundle:

``` viml
Bundle 'q335r49/textabyss'
```

And then when I start vim I do:

``` viml
:source ~/.vim/bundle/textabyss/nav.vim
```

Which all works and doesn't give me any errors.

Then I change directory:

``` viml
:cd ~/dropbox/data/planes
```

And press `<f10>`, and in the first prompt `*` and then hit enter a couple of times.
I get my files on splits, and I can pan though them, that works.

The thing is, when I hit <f10> to do anything (see the map, or anything), it beeps at me, and does nothing. I don't see any messages or anything.

I've tried debugging the code with echos I can see that when calling `<f10>` it calls `TXBdoCmd(-99)` which afterwards calls `s:doCmdKeyhandler(-99)` which then tries to execute a command from the dictionary:

``` viml
    exe get(g:TXBkyCmd,a:c,'let s:kc__msg=" Press f1 for help"')
```

Which is actually empty:

``` viml
let TXBkyCmd[-99]=""
```

I'm I doing anything wrong? Do you have any pointers as of how to get it working?

**Comment by q335r49** [comment]
Hey joakin,

Thanks for trying it out and thanks for all the debugging!

Hmm... I think what you describe is intended behavior.

Could you see if a different key other than F10 works? You can remap the global hotkey by changing the 6th line in the source (I'm working on a UI to change this right now), the line looks like:

```
"Hotkey to load plane and evoke commands
    nn <silent> <f10> :call {exists('t:txb')? 'TXBdoCmd' : 'TXBinit'}(-99)<cr>
```

If that doesn't work, can you see if starting with `vim -u NONE` and then `so nav.vim` works? There might be some weird conflict with other plugins.

The scheme to use hotkeys is actually a bit over-complicated because the default `getchar()` function in Vim moves the cursor to the command line. So to keep the cursor in the main window,  what happens is that `s:doCmdKeyHandler()` uses `feedkeys("\<plug>TxbZ")`, which then triggers a normal mapping for `<SID>getchar`, which then checks if there is a keystroke in the buffer, which then uses `feedkeys()` again if not, etc. ... all so the cursor doesn't move to the command line.

It's a really complicated loop that could probably be solved with a simple vim patch, so something might be going on with this complicated loop. So if the above doesn't work, let me know and I can provide a patched version where "<plug>TxbZ" is changed to something else.

Thanks,

Leon

**Comment by q335r49** [comment]
Could you give this a shot? I replaced the `<plug>TxbZ` with `vvvv`.Maybe there could be some issue with the `<plug>TxbZ` setting off another plugin.

http://pastebin.com/NuXYWbgv

Thanks,

Leon

**Comment by joakin** [comment]
Without my vimrc works as expected, so as you thought, there is some plugin causing interference with it.

I've tried the patched version and the behaviour is still the same (not working). I'll see if I can narrow down which plugin is interfering.

**Comment by joakin** [comment]
Also I've `ag`ed the bundles and no `TxbZ` string in there. So that may not be it.

**Comment by joakin** [comment]
After investigating through my vimrc, I've found out that plugins are ok, and the rest of it too, and the problem is that I nnoremap : and , like this:

``` viml
" Colon and Semi-colon mappings {
" Easier : reach, and saner ; map
" Now, ; goes avanti with f/F t/T and <shift-;> goes backwards
" Also command line goes to , which is better than <shift-;>
nnoremap , :
xnoremap , :
nnoremap : ,
xnoremap : ,
" }
```

So something is breaking with that. I've searched for uses of `normal` which would execute recursive mappings but found none, you use everywhere `norm!` which should be fine. I don't know what else to look at.

**Comment by q335r49** [comment]
Arg! Thanks for all the debugging! For some reason I had an `nmap` instead of an `nnoremap`, ie, i had

```
nmap <silent> <plug>TxbY<esc>[ :call <SID>getmouse()<cr>
nmap <silent> <plug>TxbY :call <SID>getchar()<cr>
nmap <silent> <plug>TxbZ :call <SID>getchar()<cr>
```

and that triggered the `:`. Changing those 3 lines to`nnoremap` worked for me. I have no idea why I used `nmap` there. Yeesh! Glad you caught that.

Leon
