### ISSUE TITLE
Plane not being saved

### ISSUE THREAD

**Issue by JKGiih** [q335r49/microviche#7]
I can't get microviche to save the plane/remember the working directory. When I open the help I get the "viminfo not set" warning. :set viminfo+=! doesn't seem to do anything, but I do have a .viminfo file and Vim writes into it as it should. Removing the old .viminfo file and letting Vim create a new one didn't do any good. I've been using a version of textabyss from a few months back (with Vim 7.4) without any issues. Do you know what the problem might be here and could I fix it by manually editing the .viminfo file somehow?

**Comment by q335r49** [comment]
If the older version works, I think I know what the problem is. On older versions I would call `:set viminfo+=!` from within the script, while on newer versions I would just throw the warning (I think this is what you're seeing?):

`':set viminfo+=!' to remember plane between sessions (or write to file with hotkey W and restore via :source file)`

This is mostly because in the newer versions the map is produced from scanning the plane itself, and not from the user putting it in manually, so nothing irrecoverible is really being stored.

I think the fix would be to put `:se viminfo+=!` -- or rather, something like `:se viminfo+='100,!`, since the `'` is required too -- in your .vimrc rather than simply executing it as a command. If you just execute it as a command, it won't be loaded on startup and the viminfo data won't be read.

**Comment by JKGiih** [comment]
Thanks, I added `:se viminfo+='100,!` in my .vimrc and it's working now.
